package socks5deploy

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"
)

// ensureDirs 建安装目录 (logs/etc 子目录), 方便 SSH 上机集中探查.
func ensureDirs(out io.Writer, req *Request) error {
	logf(out, "→ 准备安装目录: %s (logs/etc)", req.InstallDir)
	for _, sub := range []string{"logs", "etc"} {
		if err := os.MkdirAll(filepath.Join(req.InstallDir, sub), 0o755); err != nil {
			return fmt.Errorf("建安装目录失败: %w", err)
		}
	}
	_ = os.Chmod(req.InstallDir, 0o755)
	return nil
}

// writePamFile 写 PAM 配置 (pam_pwdfile 指向 htpasswd 密码文件); PAM 文件 OS 强制在 /etc/pam.d/.
func writePamFile(out io.Writer, req *Request) error {
	logf(out, "→ 写 PAM 配置: %s (pwdfile=%s)", req.PamFile, req.PwdFile)
	if err := os.MkdirAll(filepath.Dir(req.PwdFile), 0o755); err != nil {
		return fmt.Errorf("建 pwdfile 目录失败: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(req.PamFile), 0o755); err != nil {
		return fmt.Errorf("建 PAM 目录失败: %w", err)
	}
	content := fmt.Sprintf("# Generated by nook (agent socks5deploy)\n"+
		"auth     required pam_pwdfile.so pwdfile=%s\n"+
		"account  required pam_permit.so\n", req.PwdFile)
	if err := os.WriteFile(req.PamFile, []byte(content), 0o644); err != nil {
		return fmt.Errorf("写 PAM 文件失败: %w", err)
	}
	return nil
}

// writeDanteConf 写 danted.conf (已存在则带时间戳备份); PAM 用户名密码认证, 出口走 extIf.
func writeDanteConf(out io.Writer, req *Request, extIf string) error {
	logf(out, "→ 写 %s (port=%d log='%s')", req.ConfPath, req.Socks5Port, req.LogLevel)
	if err := os.MkdirAll(filepath.Dir(req.ConfPath), 0o755); err != nil {
		return fmt.Errorf("建 conf 目录失败: %w", err)
	}
	if data, err := os.ReadFile(req.ConfPath); err == nil {
		_ = os.WriteFile(fmt.Sprintf("%s.bak.%d", req.ConfPath, time.Now().Unix()), data, 0o644)
	}
	conf := fmt.Sprintf(`# Generated by nook (agent socks5deploy)
logoutput: %s

internal: 0.0.0.0 port = %d
external: %s

socksmethod: pam.username
clientmethod: none

user.privileged: root
user.notprivileged: root

client pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: %s
}

socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    socksmethod: pam.username
    log: %s
}

socks block {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    log: error
}
`, req.LogPath, req.Socks5Port, extIf, req.LogLevel, req.LogLevel)
	if err := os.WriteFile(req.ConfPath, []byte(conf), 0o644); err != nil {
		return fmt.Errorf("写 danted.conf 失败: %w", err)
	}
	return nil
}

// writeLogFile 预建日志文件 (dante logoutput 不会自己 mkdir).
func writeLogFile(req *Request) error {
	if dir := filepath.Dir(req.LogPath); dir != "." && dir != "/" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("建日志目录失败: %w", err)
		}
	}
	f, err := os.OpenFile(req.LogPath, os.O_CREATE|os.O_APPEND, 0o644)
	if err != nil {
		return fmt.Errorf("建日志文件失败: %w", err)
	}
	return f.Close()
}

// writeDropin 写 systemd drop-in: 解除 apt 包默认 sandbox (否则 dante 看不到自定义目录) + 覆盖 ExecStart 读自定义 conf.
func writeDropin(out io.Writer, req *Request) error {
	dir := filepath.Join("/etc/systemd/system", req.unit()+".service.d")
	logf(out, "→ 写 systemd drop-in (解除 sandbox + ExecStart → %s)", req.ConfPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("建 drop-in 目录失败: %w", err)
	}
	content := fmt.Sprintf(`# Nook override: 解除 apt 包 sandbox + 改 conf 路径
[Service]
InaccessibleDirectories=
ReadOnlyDirectories=
ExecStart=
ExecStart=/usr/sbin/danted -f %s
`, req.ConfPath)
	if err := os.WriteFile(filepath.Join(dir, "nook.conf"), []byte(content), 0o644); err != nil {
		return fmt.Errorf("写 drop-in 失败: %w", err)
	}
	return nil
}
