spring:
  profiles:
    active: dev
  application:
    name: nook
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.nook.biz.**.entity
  global-config:
    db-config:
      id-type: ASSIGN_UUID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      update-strategy: NOT_NULL
      insert-strategy: NOT_NULL
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    local-cache-scope: STATEMENT

sa-token:
  token-name: Authorization
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: simple-uuid
  is-read-header: true
  is-read-cookie: false

logging:
  level:
    org.springframework: WARN
